"""initial_schema

Revision ID: a728b2d08d59
Revises:
Create Date: 2026-02-23 09:35:53.515879

"""

import uuid

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "a728b2d08d59"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    is_postgres = bind.dialect.name == "postgresql"

    # uuid-ossp extension is PostgreSQL-only; SQLite has no extension mechanism.
    if is_postgres:
        op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')

    # now() is PostgreSQL-only; SQLite uses CURRENT_TIMESTAMP.
    server_default_now = sa.text("now()") if is_postgres else sa.text("CURRENT_TIMESTAMP")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("created_on", sa.DateTime(), server_default=server_default_now, nullable=True),
        sa.Column("updated_on", sa.DateTime(), server_default=server_default_now, nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_project_name"), "project", ["name"], unique=False)
    op.create_table(
        "data_file",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("file_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("file_type", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("created_on", sa.DateTime(), server_default=server_default_now, nullable=True),
        sa.Column("updated_on", sa.DateTime(), server_default=server_default_now, nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_data_file_project_id"), "data_file", ["project_id"], unique=False)
    op.create_table(
        "data_process",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("target", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("file_id", sa.UUID(), nullable=False),
        sa.Column("created_on", sa.DateTime(), server_default=server_default_now, nullable=True),
        sa.Column("updated_on", sa.DateTime(), server_default=server_default_now, nullable=True),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["data_file.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_data_process_file_id"), "data_process", ["file_id"], unique=False)
    op.create_table(
        "image_properties",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("image_size", sa.Integer(), nullable=False),
        sa.Column("batch_size", sa.Integer(), nullable=False),
        sa.Column("color_mode", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
        sa.Column("label_mode", sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
        sa.CheckConstraint("color_mode IN ('grayscale', 'rgb', 'rgba')", name="color_mode_check"),
        sa.CheckConstraint("label_mode IN ('int', 'categorical', 'binary')", name="label_mode_check"),
        sa.ForeignKeyConstraint(
            ["id"],
            ["data_file.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "model_basic",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("model_name", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("file_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("model_type", sa.Integer(), nullable=False),
        sa.Column("target_field", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("training_split", sa.Float(), nullable=False),
        sa.Column("optimizer", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("metric", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("epochs", sa.Integer(), nullable=False),
        sa.Column("loss", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("created_on", sa.DateTime(), server_default=server_default_now, nullable=True),
        sa.Column("updated_on", sa.DateTime(), server_default=server_default_now, nullable=True),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["data_file.id"],
        ),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("model_name"),
    )
    op.create_index(op.f("ix_model_basic_file_id"), "model_basic", ["file_id"], unique=False)
    op.create_index(op.f("ix_model_basic_project_id"), "model_basic", ["project_id"], unique=False)
    op.create_table(
        "model_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parameter", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("value", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("model_id", sa.Integer(), nullable=False),
        sa.Column("created_on", sa.DateTime(), server_default=server_default_now, nullable=True),
        sa.Column("updated_on", sa.DateTime(), server_default=server_default_now, nullable=True),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["model_basic.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_model_configs_model_id"), "model_configs", ["model_id"], unique=False)
    # ### end Alembic commands ###

    # Seed a sample project
    if is_postgres:
        op.execute(
            """
            INSERT INTO project (id, name, description, created_on, updated_on)
            VALUES (
                gen_random_uuid(),
                'Sample Project',
                'A sample project to get started with TensorMap',
                NOW(),
                NOW()
            )
            ON CONFLICT DO NOTHING
            """
        )
    else:
        # sa.UUID() falls back to 32-char hex (no dashes) on SQLite for every
        # value the ORM binds/compares, so the seeded row must be written in
        # that same format. Using the hyphenated str(uuid.uuid4()) here caused
        # the seeded project to be invisible to any id-based lookup.
        project_id = uuid.uuid4()
        op.execute(
            sa.text(
                """
                INSERT OR IGNORE INTO project (id, name, description, created_on, updated_on)
                VALUES (
                    :id,
                    'Sample Project',
                    'A sample project to get started with TensorMap',
                    CURRENT_TIMESTAMP,
                    CURRENT_TIMESTAMP
                )
                """
            ).bindparams(id=project_id.hex)
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_model_configs_model_id"), table_name="model_configs")
    op.drop_table("model_configs")
    op.drop_index(op.f("ix_model_basic_project_id"), table_name="model_basic")
    op.drop_index(op.f("ix_model_basic_file_id"), table_name="model_basic")
    op.drop_table("model_basic")
    op.drop_table("image_properties")
    op.drop_index(op.f("ix_data_process_file_id"), table_name="data_process")
    op.drop_table("data_process")
    op.drop_index(op.f("ix_data_file_project_id"), table_name="data_file")
    op.drop_table("data_file")
    op.drop_index(op.f("ix_project_name"), table_name="project")
    op.drop_table("project")
    # ### end Alembic commands ###
